export const Categories = [
    { id: 1, title: "Uncategorized News", code: "general" },
    { id: 2, title: "Business News", code: "business" },
    { id: 3, title: "Sports News", code: "sports" },
    { id: 4, title: "Entertainment News", code: "entertainment" },
    { id: 5, title: "Technology News", code: "technology" },
    { id: 6, title: "Health News", code: "health" },
    { id: 7, title: "Science News", code: "science" }
  ];
  

export const LanguagesCode = [
    { id: 1, title: "English", code: "en" },
    { id: 2, title: "French", code: "fr" },
    { id: 3, title: "Arabic", code: "ar" },
    { id: 4, title: "German", code: "de" },
    { id: 5, title: "Spanish", code: "es" },
    { id: 6, title: "Chinese", code: "zh" },
    { id: 7, title: "Japanese", code: "ja" },
    { id: 8, title: "Portuguese", code: "pt" },
    { id: 9, title: "Swedish", code: "se" },
    { id: 10, title: "Hebrew", code: "he" },
    { id: 11, title: "Italian", code: "it" },
    { id: 12, title: "Dutch", code: "nl" },
    { id: 13, title: "Norwegian", code: "no" }
  ];
  

export const CountryCode = [
    { id: 1, title: "Argentina", code: "ar" },
    { id: 2, title: "Australia", code: "au" },
    { id: 3, title: "Austria", code: "at" },
    { id: 4, title: "Belgium", code: "be" },
    { id: 5, title: "Brazil", code: "br" },
    { id: 6, title: "Bulgaria", code: "bg" },
    { id: 7, title: "Canada", code: "ca" },
    { id: 8, title: "China", code: "cn" },
    { id: 9, title: "Colombia", code: "co" },
    { id: 10, title: "Czech Republic", code: "cz" },
    { id: 11, title: "Egypt", code: "eg" },
    { id: 12, title: "France", code: "fr" },
    { id: 13, title: "Germany", code: "de" },
    { id: 14, title: "Greece", code: "gr" },
    { id: 15, title: "Hong Kong", code: "hk" },
    { id: 16, title: "Hungary", code: "hu" },
    { id: 17, title: "India", code: "in" },
    { id: 18, title: "Indonesia", code: "id" },
    { id: 19, title: "Ireland", code: "ie" },
    { id: 20, title: "Israel", code: "il" },
    { id: 21, title: "Italy", code: "it" },
    { id: 22, title: "Japan", code: "jp" },
    { id: 23, title: "Latvia", code: "lv" },
    { id: 24, title: "Lithuania", code: "lt" },
    { id: 25, title: "Malaysia", code: "my" },
    { id: 26, title: "Mexico", code: "mx" },
    { id: 27, title: "Morocco", code: "ma" },
    { id: 28, title: "Netherlands", code: "nl" },
    { id: 29, title: "New Zealand", code: "nz" },
    { id: 30, title: "Nigeria", code: "ng" },
    { id: 31, title: "Norway", code: "no" },
    { id: 32, title: "Philippines", code: "ph" },
    { id: 33, title: "Poland", code: "pl" },
    { id: 34, title: "Portugal", code: "pt" },
    { id: 35, title: "Romania", code: "ro" },
    { id: 36, title: "Saudi Arabia", code: "sa" },
    { id: 37, title: "Serbia", code: "rs" },
    { id: 38, title: "Singapore", code: "sg" },
    { id: 39, title: "Slovakia", code: "sk" },
    { id: 40, title: "Slovenia", code: "si" },
    { id: 41, title: "South Africa", code: "za" },
    { id: 42, title: "South Korea", code: "kr" },
    { id: 43, title: "Sweden", code: "se" },
    { id: 44, title: "Switzerland", code: "ch" },
    { id: 45, title: "Taiwan", code: "tw" },
    { id: 46, title: "Thailand", code: "th" },
    { id: 47, title: "Turkey", code: "tr" },
    { id: 48, title: "UAE", code: "ae" },
    { id: 49, title: "Ukraine", code: "ua" },
    { id: 50, title: "United Kingdom", code: "gb" },
    { id: 51, title: "United States", code: "us" },
    { id: 52, title: "Venezuela", code: "ve" }
];



